### ISSUE TITLE
PCR popup

### ISSUE THREAD

**Issue by junyu33** [somenothing/SCU-ncov_checkpoint#12]
The new wave of covid in Chengdu seems severe and it won't be too soon to discard the PCR popup.
I don't want to be called by counselor or receive wechat notification every day.

**Comment by Fuzzy9876** [comment]
目前暂无自动填写核酸信息的开发计划，因为不确定需要填写几日的核酸信息，也不确定每个人哪天是否做了核酸。建议配合防疫要求按时填写。

您可在GPL3.0许可证的限制下自行开发本功能。

> 注：本项目仅供学习交流使用，若被滥用，造成的影响与作者本人无关。
