### ISSUE TITLE
借助腾讯云服务器

### ISSUE THREAD

**Issue by Febbsa** [somenothing/SCU-ncov_checkpoint#2]
是否可以增加功能，借助腾讯云服务器实现自动打卡，而无需其他服务器或手动操作

**Comment by somenothing** [comment]
> 是否可以增加功能，借助腾讯云服务器实现自动打卡，而无需其他服务器或手动操作

按照教程所述，在服务器上配置运行环境并下载对应代码，添加计划任务后即可自动运行。
