### ISSUE TITLE
验证码突破不了

### ISSUE THREAD

**Issue by PowderL** [somenothing/SCU-ncov_checkpoint#3]
现在新系统有验证码，怎么突破

**Comment by somenothing** [comment]
> 现在新系统有验证码，怎么突破
这一段时间我计划重构所有代码，验证码部分会加入orc识别，或者使用cookies登录。

**Comment by PowderL** [comment]
使用cookie失效的可能性很高，对变成小白不够友好，我觉得可以加入ORC识别，有很多现成的接口，或者可以自己开发一个

**Comment by somenothing** [comment]
针对此问题已经更新
